/**
 * Complete SSC task libraries by function × period.
 * Materialized onto checklist instances by the Phase 66 engine.
 */

import type { SscTaskTemplate } from './types';

function t(
  partial: Omit<SscTaskTemplate, 'per_company'> & { per_company?: boolean },
): SscTaskTemplate {
  return { per_company: partial.per_company ?? true, ...partial };
}

const FINANCE: SscTaskTemplate[] = [
  // Weekly / as needed
  t({
    key: 'fin.w.exception_queues',
    title: 'Clear finance exception queues',
    description: 'Review and resolve payment, AP/AR, and feed exceptions.',
    function: 'finance',
    period_type: 'weekly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'fin.w.failed_payments',
    title: 'Failed payment / collections follow-ups',
    description: 'Chase failed payments and overdue collections items.',
    function: 'finance',
    period_type: 'weekly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'fin.w.cash_variance',
    title: 'Cash variance check',
    description: 'Compare expected vs actual cash and flag material variance.',
    function: 'finance',
    period_type: 'weekly',
    owner_role: 'coo',
    risk_level: 'critical',
  }),
  t({
    key: 'fin.w.urgent_invoice',
    title: 'Urgent invoice / bill issues',
    description: 'Resolve blocked invoices/bills and vendor disputes.',
    function: 'finance',
    period_type: 'as_needed',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'fin.w.anomaly_triage',
    title: 'Finance anomaly alert triage',
    description: 'Review Phase 55 anomaly alerts; escalate dual-approve items.',
    function: 'finance',
    period_type: 'as_needed',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  // Monthly
  t({
    key: 'fin.m.close_checklist',
    title: 'Month-end close checklist',
    description: 'Complete month-end close pack and sign-off path.',
    function: 'finance',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'critical',
  }),
  t({
    key: 'fin.m.reconciliations',
    title: 'Bank & balance reconciliations',
    description: 'Reconcile bank, credit card, and key balance sheet accounts.',
    function: 'finance',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'fin.m.kpi_pack',
    title: 'KPI pack refresh',
    description: 'Refresh finance KPI pack for parent and portfolio companies.',
    function: 'finance',
    period_type: 'monthly',
    owner_role: 'coo',
    risk_level: 'normal',
  }),
  t({
    key: 'fin.m.sub_intake',
    title: 'Subsidiary financial data intake / validation',
    description: 'Pull and validate subsidiary finance summaries into Tage.',
    function: 'finance',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'fin.m.close_signoff',
    title: 'Close sign-off',
    description: 'Obtain month-end close sign-off from accountable owner.',
    function: 'finance',
    period_type: 'monthly',
    owner_role: 'coo',
    risk_level: 'critical',
  }),
  // Quarterly
  t({
    key: 'fin.q.review_pack',
    title: 'Quarterly finance review pack',
    description: 'Assemble quarterly review pack for Visionary/COO.',
    function: 'finance',
    period_type: 'quarterly',
    owner_role: 'coo',
    risk_level: 'high',
  }),
  t({
    key: 'fin.q.budget_vs_actual',
    title: 'Budget vs actual review',
    description: 'Review budget vs actual and variance explanations.',
    function: 'finance',
    period_type: 'quarterly',
    owner_role: 'coo',
    risk_level: 'high',
  }),
  t({
    key: 'fin.q.bs_cash',
    title: 'Balance sheet / cash review',
    description: 'Review BS integrity, cash position, and runway.',
    function: 'finance',
    period_type: 'quarterly',
    owner_role: 'partner',
    risk_level: 'critical',
  }),
  t({
    key: 'fin.q.tax_compliance',
    title: 'Tax / compliance checkpoint',
    description: 'Confirm tax filings/calendar and compliance checkpoints.',
    function: 'finance',
    period_type: 'quarterly',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  // Annual
  t({
    key: 'fin.a.year_end_close',
    title: 'Year-end close',
    description: 'Execute year-end close checklist and roll-forward.',
    function: 'finance',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'critical',
  }),
  t({
    key: 'fin.a.annual_package',
    title: 'Annual financial package',
    description: 'Produce annual financial package for leadership.',
    function: 'finance',
    period_type: 'annual',
    owner_role: 'coo',
    risk_level: 'high',
  }),
  t({
    key: 'fin.a.audit_support',
    title: 'Audit support package',
    description: 'Assemble evidence package for external/internal audit.',
    function: 'finance',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'fin.a.policy_control',
    title: 'Policy / control review',
    description: 'Review finance policies and key controls.',
    function: 'finance',
    period_type: 'annual',
    owner_role: 'coo',
    risk_level: 'normal',
  }),
];

const HR: SscTaskTemplate[] = [
  t({
    key: 'hr.w.jml_open',
    title: 'Open joiner / mover / leaver items',
    description: 'Close open JML workflow steps across companies.',
    function: 'hr',
    period_type: 'weekly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'hr.w.onboarding_incomplete',
    title: 'Incomplete onboarding / offboarding steps',
    description: 'Chase incomplete onboarding and offboarding checklist steps.',
    function: 'hr',
    period_type: 'weekly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'hr.w.urgent_access',
    title: 'Urgent access / HR issues',
    description: 'Triage urgent access and HR service tickets.',
    function: 'hr',
    period_type: 'as_needed',
    owner_role: 'service_lead',
    risk_level: 'critical',
  }),
  t({
    key: 'hr.m.roster_recon',
    title: 'Roster reconciliation',
    description: 'Reconcile active roster vs identity and payroll signals.',
    function: 'hr',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'hr.m.access_sample',
    title: 'Access rights review sample',
    description: 'Sample access rights for joiners/movers/leavers this month.',
    function: 'hr',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'hr.m.training_due',
    title: 'Training / compliance due items',
    description: 'Clear overdue training and compliance acknowledgments.',
    function: 'hr',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'hr.m.headcount_report',
    title: 'Headcount and changes report',
    description: 'Publish headcount and change report by company.',
    function: 'hr',
    period_type: 'monthly',
    owner_role: 'coo',
    risk_level: 'normal',
  }),
  t({
    key: 'hr.q.policy_ack',
    title: 'Policy acknowledgment checks',
    description: 'Verify required policy acknowledgments are current.',
    function: 'hr',
    period_type: 'quarterly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'hr.q.perf_cycle',
    title: 'Performance cycle checkpoint',
    description: 'Confirm performance cycle milestones are on track.',
    function: 'hr',
    period_type: 'quarterly',
    owner_role: 'coo',
    risk_level: 'normal',
  }),
  t({
    key: 'hr.q.comp_review',
    title: 'Compensation / review process checks',
    description: 'Validate compensation review process readiness.',
    function: 'hr',
    period_type: 'quarterly',
    owner_role: 'partner',
    risk_level: 'high',
  }),
  t({
    key: 'hr.q.risk_compliance',
    title: 'HR risk / compliance review',
    description: 'Review HR risk register and compliance open items.',
    function: 'hr',
    period_type: 'quarterly',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  t({
    key: 'hr.a.handbook',
    title: 'Handbook / policy annual review',
    description: 'Complete handbook and policy annual review.',
    function: 'hr',
    period_type: 'annual',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  t({
    key: 'hr.a.certifications',
    title: 'Required compliance certifications',
    description: 'Confirm required HR compliance certifications.',
    function: 'hr',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'hr.a.audit_package',
    title: 'Annual HR audit package',
    description: 'Assemble annual HR audit evidence package.',
    function: 'hr',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'hr.a.benefits_renewals',
    title: 'Benefits / compliance renewals',
    description: 'Track benefits and compliance renewals to completion.',
    function: 'hr',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
];

const IT: SscTaskTemplate[] = [
  t({
    key: 'it.w.incident_queue',
    title: 'Incident queue review',
    description: 'Triage open IT incidents and SLA breaches.',
    function: 'it',
    period_type: 'weekly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'it.w.access_exceptions',
    title: 'Access provisioning exceptions',
    description: 'Clear provisioning exceptions and dual-approve backlog.',
    function: 'it',
    period_type: 'weekly',
    owner_role: 'service_lead',
    risk_level: 'critical',
  }),
  t({
    key: 'it.w.security_alerts',
    title: 'Security alert triage',
    description: 'Triage security alerts; escalate high-risk items.',
    function: 'it',
    period_type: 'as_needed',
    owner_role: 'service_lead',
    risk_level: 'critical',
  }),
  t({
    key: 'it.w.backup_exceptions',
    title: 'Backup / monitoring exceptions',
    description: 'Resolve backup and monitoring exceptions.',
    function: 'it',
    period_type: 'as_needed',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'it.m.user_access_review',
    title: 'User access review',
    description: 'Complete monthly user access review sample.',
    function: 'it',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'it.m.asset_license',
    title: 'Asset / license reconciliation',
    description: 'Reconcile hardware assets and software licenses.',
    function: 'it',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'it.m.patch_posture',
    title: 'Patch / security posture check',
    description: 'Review patch and Intune security posture.',
    function: 'it',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'it.m.integration_health',
    title: 'Integration health review',
    description: 'Review integration health and breaker status.',
    function: 'it',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'it.q.dr_restore',
    title: 'DR / restore test checkpoint',
    description: 'Confirm DR/restore test evidence for the quarter.',
    function: 'it',
    period_type: 'quarterly',
    owner_role: 'coo',
    risk_level: 'critical',
  }),
  t({
    key: 'it.q.vendor_security',
    title: 'Vendor / security review',
    description: 'Review critical vendor security posture.',
    function: 'it',
    period_type: 'quarterly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'it.q.privileged_access',
    title: 'Privileged access review',
    description: 'Review privileged accounts and dual-control paths.',
    function: 'it',
    period_type: 'quarterly',
    owner_role: 'admin',
    risk_level: 'critical',
  }),
  t({
    key: 'it.q.systems_inventory',
    title: 'Systems inventory validation',
    description: 'Validate systems inventory completeness.',
    function: 'it',
    period_type: 'quarterly',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'it.a.security_policy',
    title: 'Security policy review',
    description: 'Annual security policy review and updates.',
    function: 'it',
    period_type: 'annual',
    owner_role: 'coo',
    risk_level: 'high',
  }),
  t({
    key: 'it.a.access_recert',
    title: 'Annual access recertification',
    description: 'Complete annual access recertification for all companies.',
    function: 'it',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'critical',
  }),
  t({
    key: 'it.a.audit_package',
    title: 'Annual IT audit package',
    description: 'Assemble annual IT audit evidence package.',
    function: 'it',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'it.a.license_renewals',
    title: 'License / contract renewals',
    description: 'Track IT license and contract renewals.',
    function: 'it',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
];

const MARKETING: SscTaskTemplate[] = [
  t({
    key: 'mkt.w.publish_approvals',
    title: 'Campaign / publish approvals due',
    description: 'Clear due campaign and publish approvals.',
    function: 'marketing',
    period_type: 'weekly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'mkt.w.channel_incidents',
    title: 'Channel incidents',
    description: 'Resolve channel outages and publishing incidents.',
    function: 'marketing',
    period_type: 'weekly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'mkt.w.lead_quality',
    title: 'Lead-quality exceptions',
    description: 'Review lead-quality exceptions and attribution gaps.',
    function: 'marketing',
    period_type: 'as_needed',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.w.brand_reputation',
    title: 'Urgent brand / reputation items',
    description: 'Triage urgent brand and reputation issues.',
    function: 'marketing',
    period_type: 'as_needed',
    owner_role: 'coo',
    risk_level: 'critical',
  }),
  t({
    key: 'mkt.m.perf_pack',
    title: 'Performance pack by company',
    description: 'Publish marketing performance pack per company.',
    function: 'marketing',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.m.content_calendar',
    title: 'Content / calendar completion review',
    description: 'Review content calendar completion and SLA.',
    function: 'marketing',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.m.spend_vs_plan',
    title: 'Spend vs plan',
    description: 'Compare paid spend vs plan; flag overruns.',
    function: 'marketing',
    period_type: 'monthly',
    owner_role: 'coo',
    risk_level: 'high',
  }),
  t({
    key: 'mkt.m.attribution',
    title: 'Attribution / quality checks',
    description: 'Validate attribution and quality checks.',
    function: 'marketing',
    period_type: 'monthly',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.q.channel_strategy',
    title: 'Channel strategy review',
    description: 'Quarterly channel strategy review.',
    function: 'marketing',
    period_type: 'quarterly',
    owner_role: 'coo',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.q.funnel',
    title: 'Funnel conversion review',
    description: 'Review funnel conversion and drop-offs.',
    function: 'marketing',
    period_type: 'quarterly',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
  t({
    key: 'mkt.q.brand_asset_audit',
    title: 'Brand / asset audit sample',
    description: 'Sample brand assets for guideline compliance.',
    function: 'marketing',
    period_type: 'quarterly',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.q.agency_vendor',
    title: 'Agency / vendor performance',
    description: 'Review agency/vendor performance vs SOW.',
    function: 'marketing',
    period_type: 'quarterly',
    owner_role: 'coo',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.a.annual_plan',
    title: 'Annual marketing plan review',
    description: 'Complete annual marketing plan review.',
    function: 'marketing',
    period_type: 'annual',
    owner_role: 'coo',
    risk_level: 'high',
  }),
  t({
    key: 'mkt.a.brand_guidelines',
    title: 'Brand guideline review',
    description: 'Annual brand guideline review and updates.',
    function: 'marketing',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.a.perf_package',
    title: 'Annual performance package',
    description: 'Assemble annual marketing performance package.',
    function: 'marketing',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'normal',
  }),
  t({
    key: 'mkt.a.tool_renewals',
    title: 'Tool / contract renewals',
    description: 'Track marketing tool and contract renewals.',
    function: 'marketing',
    period_type: 'annual',
    owner_role: 'service_lead',
    risk_level: 'high',
  }),
];

const LEGAL: SscTaskTemplate[] = [
  t({
    key: 'leg.w.urgent_matters',
    title: 'Urgent contracts / matters',
    description: 'Triage urgent contracts and legal matters.',
    function: 'legal',
    period_type: 'weekly',
    owner_role: 'counsel_ops',
    risk_level: 'critical',
  }),
  t({
    key: 'leg.w.expiring',
    title: 'Expiring items',
    description: 'Review contracts and envelopes nearing expiry.',
    function: 'legal',
    period_type: 'weekly',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  t({
    key: 'leg.w.high_risk',
    title: 'High-priority risk issues',
    description: 'Escalate high-priority legal risk issues (human send/sign only).',
    function: 'legal',
    period_type: 'as_needed',
    owner_role: 'counsel_ops',
    risk_level: 'critical',
  }),
  t({
    key: 'leg.m.matter_aging',
    title: 'Matter aging review',
    description: 'Review matter aging and stalled envelopes.',
    function: 'legal',
    period_type: 'monthly',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  t({
    key: 'leg.m.cycle_time',
    title: 'Contract cycle-time review',
    description: 'Review contract cycle-time and bottlenecks.',
    function: 'legal',
    period_type: 'monthly',
    owner_role: 'counsel_ops',
    risk_level: 'normal',
  }),
  t({
    key: 'leg.m.compliance_followups',
    title: 'Compliance follow-ups',
    description: 'Clear compliance follow-ups and DocuSign exceptions.',
    function: 'legal',
    period_type: 'monthly',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  t({
    key: 'leg.m.outside_counsel',
    title: 'Outside counsel spend check',
    description: 'Review outside counsel spend vs plan (no auto-payment).',
    function: 'legal',
    period_type: 'monthly',
    owner_role: 'coo',
    risk_level: 'high',
  }),
  t({
    key: 'leg.q.regulatory',
    title: 'Regulatory / compliance review',
    description: 'Quarterly regulatory and compliance review.',
    function: 'legal',
    period_type: 'quarterly',
    owner_role: 'counsel_ops',
    risk_level: 'critical',
  }),
  t({
    key: 'leg.q.policy_legal',
    title: 'Policy legal review checkpoint',
    description: 'Legal review checkpoint on policy portfolio.',
    function: 'legal',
    period_type: 'quarterly',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  t({
    key: 'leg.q.risk_register',
    title: 'Risk register review',
    description: 'Review legal risk register open items.',
    function: 'legal',
    period_type: 'quarterly',
    owner_role: 'partner',
    risk_level: 'high',
  }),
  t({
    key: 'leg.q.template_gov',
    title: 'Template governance review',
    description: 'Review DocuSign template governance and dual-control.',
    function: 'legal',
    period_type: 'quarterly',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  t({
    key: 'leg.a.audit_package',
    title: 'Annual legal / compliance audit package',
    description: 'Assemble annual legal/compliance audit package.',
    function: 'legal',
    period_type: 'annual',
    owner_role: 'counsel_ops',
    risk_level: 'high',
  }),
  t({
    key: 'leg.a.policy_portfolio',
    title: 'Policy portfolio review',
    description: 'Annual policy portfolio review.',
    function: 'legal',
    period_type: 'annual',
    owner_role: 'counsel_ops',
    risk_level: 'normal',
  }),
  t({
    key: 'leg.a.insurance_renewals',
    title: 'Insurance / legal renewals support',
    description: 'Support insurance and legal renewals.',
    function: 'legal',
    period_type: 'annual',
    owner_role: 'coo',
    risk_level: 'high',
  }),
  t({
    key: 'leg.a.good_standing',
    title: 'Entity good-standing / compliance support',
    description: 'Confirm entity good-standing and compliance support.',
    function: 'legal',
    period_type: 'annual',
    owner_role: 'counsel_ops',
    risk_level: 'critical',
  }),
];

export const SSC_TASK_LIBRARY: SscTaskTemplate[] = [
  ...FINANCE,
  ...HR,
  ...IT,
  ...MARKETING,
  ...LEGAL,
];

export function templatesFor(
  functionKey: SscTaskTemplate['function'] | 'all',
  periodType: SscTaskTemplate['period_type'],
): SscTaskTemplate[] {
  return SSC_TASK_LIBRARY.filter(
    (x) =>
      (functionKey === 'all' || x.function === functionKey) &&
      x.period_type === periodType,
  );
}

export function libraryStats() {
  const byFn: Record<string, number> = {};
  const byPeriod: Record<string, number> = {};
  for (const item of SSC_TASK_LIBRARY) {
    byFn[item.function] = (byFn[item.function] ?? 0) + 1;
    byPeriod[item.period_type] = (byPeriod[item.period_type] ?? 0) + 1;
  }
  return {
    total: SSC_TASK_LIBRARY.length,
    by_function: byFn,
    by_period: byPeriod,
  };
}
