-- Email Campaign Center schema (additive). No vendor ESP.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
alter table public.contacts add column if not exists email_permission text not null default 'opted_in';
alter table public.contacts add column if not exists email_opted_out_at timestamptz;
alter table public.contacts add column if not exists email_opted_out_reason text;
alter table public.contacts add column if not exists engagement_score numeric not null default 0;
alter table public.contacts add column if not exists lifecycle text;
do $$ begin
  alter table public.contacts drop constraint if exists contacts_email_permission_check;
  alter table public.contacts add constraint contacts_email_permission_check check (email_permission in ('opted_in','opted_out','unknown'));
exception when others then null; end $$;
create table if not exists public.ecc_entity_settings (
  entity_id text primary key check (entity_id ~ '^ENT-[A-Z0-9-]{1,32}$'),
  campaign_enabled boolean not null default true, kill_switch boolean not null default false,
  default_permission text not null default 'opted_in',
  quiet_hours_json jsonb not null default '{"start":21,"end":8}'::jsonb,
  frequency_cap_json jsonb not null default '{"per_7d":7,"per_30d":20}'::jsonb,
  mutex_policy_json jsonb not null default '{"global_max":3,"on_conflict":"block"}'::jsonb,
  require_domain_verified boolean not null default false, physical_address text,
  brand_kit_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
insert into public.ecc_entity_settings (entity_id, campaign_enabled, physical_address) values
 ('ENT-FIRM',true,'Tage Venture Capital — San Diego, CA'),('ENT-R619',true,'Recruit 619 — San Diego, CA'),
 ('ENT-SIGNENT',true,'Signent HR — San Diego, CA'),('ENT-INDA',true,'Instant NDA — San Diego, CA')
on conflict (entity_id) do nothing;
create table if not exists public.ecc_brand_kits (id uuid primary key default gen_random_uuid(), entity_id text not null unique, logo_url text, colors_json jsonb not null default '{}'::jsonb, fonts_json jsonb not null default '{}'::jsonb, footer_html text, physical_address text not null default '', social_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ecc_sending_domains (id uuid primary key default gen_random_uuid(), entity_id text not null, domain text not null, subdomain text, spf_ok boolean not null default false, dkim_ok boolean not null default false, dmarc_ok boolean not null default false, dkim_selector text, status text not null default 'pending', dns_records_json jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(entity_id, domain));
create table if not exists public.ecc_sending_identities (id uuid primary key default gen_random_uuid(), entity_id text not null, from_name text not null, from_email text not null, reply_to text, identity_type text not null default 'marketing', is_default boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.ecc_provider_accounts (id uuid primary key default gen_random_uuid(), entity_id text not null, provider text not null check (provider in ('owned_mta','graph')), status text not null default 'active', created_at timestamptz not null default now(), unique(entity_id, provider));
insert into public.ecc_provider_accounts (entity_id, provider) values ('ENT-FIRM','graph'),('ENT-R619','graph'),('ENT-SIGNENT','graph'),('ENT-INDA','graph') on conflict do nothing;
create table if not exists public.ecc_templates (id uuid primary key default gen_random_uuid(), entity_id text not null, name text not null, category text not null default 'general', subject text not null default '', html text not null default '', status text not null default 'draft', include_signature_default boolean not null default false, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ecc_lists (id uuid primary key default gen_random_uuid(), entity_id text not null, name text not null, list_type text not null default 'static', description text, count_cached int not null default 0, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ecc_list_members (list_id uuid not null references public.ecc_lists(id) on delete cascade, contact_id uuid not null references public.contacts(id) on delete cascade, added_at timestamptz not null default now(), source text not null default 'manual', primary key(list_id, contact_id));
create table if not exists public.ecc_segments (id uuid primary key default gen_random_uuid(), entity_id text not null, name text not null, definition_json jsonb not null default '{"op":"and","rules":[]}'::jsonb, is_dynamic boolean not null default true, count_cached int not null default 0, last_materialized_at timestamptz, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ecc_segment_members (segment_id uuid not null references public.ecc_segments(id) on delete cascade, contact_id uuid not null references public.contacts(id) on delete cascade, entered_at timestamptz not null default now(), exited_at timestamptz, primary key(segment_id, contact_id));
create table if not exists public.ecc_preference_topics (id uuid primary key default gen_random_uuid(), entity_id text not null, topic_key text not null, label text not null, description text, default_subscribed boolean not null default true, unique(entity_id, topic_key));
insert into public.ecc_preference_topics (entity_id, topic_key, label, description) select e,t,l,d from (values ('ENT-FIRM'),('ENT-R619'),('ENT-SIGNENT'),('ENT-INDA')) e(e) cross join (values ('product_updates','Product updates','Announcements'),('newsletters','Newsletters','Newsletters'),('recruiting_alerts','Recruiting alerts','Jobs'),('nda_reminders','NDA reminders','Signatures')) x(t,l,d) on conflict do nothing;
create table if not exists public.ecc_consent_records (id uuid primary key default gen_random_uuid(), entity_id text not null, contact_id uuid, email_normalized text not null, channel text not null default 'email', topic text not null default 'marketing', status text not null check (status in ('opt_in','opt_out','pending')), source text not null default 'system', evidence_json jsonb not null default '{}'::jsonb, occurred_at timestamptz not null default now());
create table if not exists public.ecc_suppressions (id uuid primary key default gen_random_uuid(), entity_id text not null, email_normalized text not null, reason text not null check (reason in ('bounce_hard','complaint','unsub','manual','legal')), source text not null default 'system', created_at timestamptz not null default now(), expires_at timestamptz, unique(entity_id, email_normalized));
create table if not exists public.ecc_campaigns (id uuid primary key default gen_random_uuid(), entity_id text not null, name text not null, campaign_type text not null default 'blast', status text not null default 'draft', audience_type text, audience_id uuid, template_id uuid references public.ecc_templates(id) on delete set null, subject text not null default '', body_html text not null default '', schedule_at timestamptz, timezone text not null default 'America/Los_Angeles', approval_state text not null default 'draft', delivery_plane text not null default 'controlled_graph' check (delivery_plane in ('graph','owned_mta','controlled_graph','auto')), created_by uuid, owner_id uuid, sent_at timestamptz, stats_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists ecc_campaigns_entity_idx on public.ecc_campaigns(entity_id, updated_at desc);
create table if not exists public.ecc_campaign_approvals (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references public.ecc_campaigns(id) on delete cascade, from_state text not null, to_state text not null, actor_id uuid, comment text, at timestamptz not null default now());
create table if not exists public.ecc_sends (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references public.ecc_campaigns(id) on delete cascade, entity_id text not null, started_at timestamptz not null default now(), finished_at timestamptz, status text not null default 'queued', planned_count int not null default 0, sent_count int not null default 0, error_count int not null default 0, skipped_count int not null default 0, idempotency_key text);
create table if not exists public.ecc_send_jobs (id uuid primary key default gen_random_uuid(), entity_id text not null, send_id uuid not null references public.ecc_sends(id) on delete cascade, campaign_id uuid not null references public.ecc_campaigns(id) on delete cascade, batch_index int not null default 0, contact_ids uuid[] not null default '{}', status text not null default 'queued', idempotency_key text not null unique, scheduled_for timestamptz not null default now(), started_at timestamptz, finished_at timestamptz, error text, reply_to text);
create index if not exists ecc_send_jobs_poll_idx on public.ecc_send_jobs(status, scheduled_for) where status='queued';
create table if not exists public.ecc_send_messages (id uuid primary key default gen_random_uuid(), send_id uuid not null references public.ecc_sends(id) on delete cascade, campaign_id uuid not null references public.ecc_campaigns(id) on delete cascade, entity_id text not null, contact_id uuid, email text not null, provider text not null default 'graph', provider_message_id text, status text not null default 'queued', subject_rendered text, tracking_token text unique, skip_reason text, metadata_json jsonb not null default '{}'::jsonb, sent_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.ecc_campaign_recipients (campaign_id uuid not null references public.ecc_campaigns(id) on delete cascade, contact_id uuid not null references public.contacts(id) on delete cascade, email text, sent_at timestamptz, open_count int not null default 0, click_count int not null default 0, replied boolean not null default false, score numeric not null default 0, last_activity_at timestamptz, primary key(campaign_id, contact_id));
create table if not exists public.ecc_engagement_events (id uuid primary key default gen_random_uuid(), entity_id text not null, send_message_id uuid, contact_id uuid, campaign_id uuid, event_type text not null, url text, user_agent text, is_machine_open boolean not null default false, occurred_at timestamptz not null default now());
create table if not exists public.ecc_journeys (id uuid primary key default gen_random_uuid(), entity_id text not null, name text not null, journey_type text not null default 'sequence', status text not null default 'draft', graph_json jsonb not null default '{"nodes":[],"edges":[]}'::jsonb, mutex_group text, default_delivery_plane text not null default 'auto', created_by uuid, owner_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ecc_journey_enrollments (id uuid primary key default gen_random_uuid(), journey_id uuid not null references public.ecc_journeys(id) on delete cascade, entity_id text not null, contact_id uuid not null references public.contacts(id) on delete cascade, owner_id uuid, state text not null default 'active', entered_at timestamptz not null default now(), exited_at timestamptz, exit_reason text, source text not null default 'campaign_ui');
create table if not exists public.ecc_dialer_attempts (id uuid primary key default gen_random_uuid(), entity_id text not null, contact_id uuid, owner_id uuid, enrollment_id uuid, step_id text, outcome text, vm_dropped boolean not null default false, started_at timestamptz not null default now(), ended_at timestamptz, metadata_json jsonb not null default '{}'::jsonb);
create table if not exists public.ecc_paired_sends (attempt_id uuid primary key references public.ecc_dialer_attempts(id) on delete cascade, send_message_id uuid, enrollment_id uuid, step_id text, status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists public.ecc_envelope_actions (id uuid primary key default gen_random_uuid(), entity_id text not null, contact_id uuid, library_document_id text not null, docusign_envelope_id text, campaign_id uuid, journey_enrollment_id uuid, status text not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ecc_conversation_state (contact_id uuid not null references public.contacts(id) on delete cascade, entity_id text not null, state text not null default 'conversing', reason text, since timestamptz not null default now(), actor_id uuid, primary key(contact_id, entity_id));
create table if not exists public.ecc_user_signatures (user_id uuid not null, entity_id text not null, html text not null default '', plain text not null default '', source text not null default 'portal', updated_at timestamptz not null default now(), primary key(user_id, entity_id));
create table if not exists public.ecc_audit_log (id uuid primary key default gen_random_uuid(), entity_id text not null, actor_id uuid, action text not null, object_type text not null, object_id text, before_json jsonb, after_json jsonb, at timestamptz not null default now());
create table if not exists public.ecc_pref_tokens (token text primary key, entity_id text not null, contact_id uuid, email_normalized text not null, created_at timestamptz not null default now());
create table if not exists public.ecc_command_center_cache (user_id uuid not null, entity_id text not null, payload_json jsonb not null default '{}'::jsonb, refreshed_at timestamptz not null default now(), primary key(user_id, entity_id));
insert into public.ecc_templates (entity_id, name, category, subject, html, status) values
 ('ENT-R619','Candidate nurture','recruiting','Quick note','<p>Hi {{contact.first_name | default: "there"}},</p>','active'),
 ('ENT-SIGNENT','Onboarding day 1','hr','Welcome','<p>Hi {{contact.first_name | default: "there"}},</p>','active'),
 ('ENT-INDA','NDA reminder','nda','Please sign','<p>Hi {{contact.first_name | default: "there"}},</p>','active'),
 ('ENT-FIRM','Portfolio update','newsletter','Update','<p>Hello {{contact.first_name | default: "there"}},</p>','active') on conflict do nothing;
do $$ declare t text; begin
  foreach t in array array['ecc_entity_settings','ecc_brand_kits','ecc_sending_domains','ecc_templates','ecc_lists','ecc_segments','ecc_consent_records','ecc_suppressions','ecc_campaigns','ecc_sends','ecc_send_jobs','ecc_send_messages','ecc_campaign_recipients','ecc_engagement_events','ecc_journeys','ecc_journey_enrollments','ecc_dialer_attempts','ecc_conversation_state','ecc_audit_log','ecc_command_center_cache'] loop
    execute format('alter table public.%I enable row level security', t);
    begin execute format('create policy %I on public.%I for select to authenticated using (public.is_firm_wide_access() or public.can_access_entity(entity_id))', t||'_select', t);
    exception when others then null; end;
  end loop;
end $$;
