import Link from 'next/link';
import { NotificationPrefsForm } from '@/components/settings/notification-prefs-form';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';

export default function NotificationSettingsPage() {
  return (
    <div className="space-y-6">
      <header className="space-y-2">
        <Link
          href="/activity"
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          ← Activity
        </Link>
        <h1 className="font-heading text-3xl font-semibold tracking-tight text-[#3a414f]">
          Notification preferences
        </h1>
        <p className="max-w-2xl text-sm text-muted-foreground">
          Control chat alerts, mention notifications, and email digest cadence.
        </p>
      </header>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Delivery</CardTitle>
          <CardDescription>
            Digests are generated by{' '}
            <code className="text-xs">POST /api/notifications/digest</code>{' '}
            (cron or manual). Email send is best-effort when{' '}
            <code className="text-xs">RESEND_API_KEY</code> is set.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <NotificationPrefsForm />
        </CardContent>
      </Card>
    </div>
  );
}
