import Link from 'next/link';
import { NotificationPrefsForm } from '@/components/settings/notification-prefs-form';
import { PracticalNotificationsPhase59Client } from '@/components/settings/practical-notifications-phase59-client';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { getPracticalNotificationsPhase59Report } from '@/lib/notifications/practical-notifications-phase59-server';
import { getSessionContext } from '@/lib/rbac/session';

export default async function NotificationSettingsPage() {
  const ctx = await getSessionContext();
  const report = await getPracticalNotificationsPhase59Report(null);
  const canWrite = Boolean(ctx?.profile?.id);

  return (
    <div className="space-y-6">
      <header className="space-y-2">
        <div className="flex flex-wrap items-center gap-3 text-sm">
          <Link
            href="/activity"
            className="text-muted-foreground hover:text-foreground"
          >
            ← Activity
          </Link>
          <Link
            href="/home"
            className="text-muted-foreground underline-offset-4 hover:underline"
          >
            Open Home / Think Tank →
          </Link>
        </div>
        <h1 className="font-heading text-3xl font-semibold tracking-tight text-[#3a414f]">
          Notification preferences
        </h1>
        <p className="max-w-2xl text-sm text-muted-foreground">
          Preference center for chat, mentions, owner/assignee routing, and
          optional critical email digests. Reliability over channel expansion —
          not a full push product.
        </p>
      </header>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Delivery</CardTitle>
          <CardDescription>
            Digests are generated by{' '}
            <code className="text-xs">POST /api/notifications/digest</code>{' '}
            (cron or manual). Critical email is best-effort when{' '}
            <code className="text-xs">RESEND_API_KEY</code> is set and
            critical-digest prefs are on.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <NotificationPrefsForm />
        </CardContent>
      </Card>

      <PracticalNotificationsPhase59Client
        report={report}
        canWrite={canWrite}
      />
    </div>
  );
}
