import type { ReProcessTemplate, ReRoute, ReStage } from '@/lib/types';

/** RE Process Library from Excel — filter by route (Both + specific). */
export const RE_PROCESS_LIBRARY: ReProcessTemplate[] = [
  {
    lib_id: 'RE-01',
    route: 'Both',
    process_stage: 'Sourced',
    title: 'Log asset: address, route, type, source, ask',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer',
    what_good_looks_like: 'RE-### complete',
  },
  {
    lib_id: 'RE-02',
    route: 'Both',
    process_stage: 'Sourced',
    title: 'Thesis fit: market, size, hold thesis',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer',
    what_good_looks_like: 'In/out of box stated',
  },
  {
    lib_id: 'RE-03',
    route: 'Residential',
    process_stage: 'Screen',
    title: 'Pull comps (sold/active); condition photos',
    default_priority: 'High',
    owner_role: 'RE Sourcer — Resi',
    what_good_looks_like: '3+ comps within 0.5–1 mi',
  },
  {
    lib_id: 'RE-04',
    route: 'Commercial',
    process_stage: 'Screen',
    title: 'Review OM/CIM: rent roll, T-12, occupancy',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer — CRE',
    what_good_looks_like: 'NOI bridge started',
  },
  {
    lib_id: 'RE-05',
    route: 'Both',
    process_stage: 'Screen',
    title: 'Title / tax / flood / zoning quick flags',
    default_priority: 'High',
    owner_role: 'RE Sourcer',
    what_good_looks_like: 'Red flags listed',
  },
  {
    lib_id: 'RE-06',
    route: 'Residential',
    process_stage: 'Underwriting',
    title: 'ARV, rehab budget, all-in basis, exit yield',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer — Resi',
    what_good_looks_like: 'RE Underwrite Resi block filled',
  },
  {
    lib_id: 'RE-07',
    route: 'Commercial',
    process_stage: 'Underwriting',
    title: 'NOI, cap rate, debt sketch, sensitivity',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer — CRE',
    what_good_looks_like: 'RE Underwrite CRE block filled',
  },
  {
    lib_id: 'RE-08',
    route: 'Both',
    process_stage: 'Underwriting',
    title: 'IC / partner go-no-go on offer price',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Authority to offer',
  },
  {
    lib_id: 'RE-09',
    route: 'Both',
    process_stage: 'Offer',
    title: 'Submit offer / LOI; track response',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer',
    what_good_looks_like: 'Offer $ on pipeline',
  },
  {
    lib_id: 'RE-10',
    route: 'Both',
    process_stage: 'LOI / PSA',
    title: 'Negotiate PSA; earnest money; contingencies',
    default_priority: 'Critical',
    owner_role: 'Counsel + Sourcer',
    what_good_looks_like: 'PSA fully executed',
  },
  {
    lib_id: 'RE-11',
    route: 'Residential',
    process_stage: 'Diligence',
    title: 'Home inspection, pest, sewer/septic as needed',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer — Resi',
    what_good_looks_like: 'Repair credit or walk',
  },
  {
    lib_id: 'RE-12',
    route: 'Commercial',
    process_stage: 'Diligence',
    title: 'Phase I ESA; PCA if needed; survey',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer — CRE',
    what_good_looks_like: 'Environmental clear or escrow',
  },
  {
    lib_id: 'RE-13',
    route: 'Commercial',
    process_stage: 'Diligence',
    title: 'Lease abstract; estoppel plan; CAM audit',
    default_priority: 'High',
    owner_role: 'RE Sourcer — CRE',
    what_good_looks_like: 'Rollover risk mapped',
  },
  {
    lib_id: 'RE-14',
    route: 'Both',
    process_stage: 'Diligence',
    title: 'Appraisal / lender package if financed',
    default_priority: 'High',
    owner_role: 'Ops / Sourcer',
    what_good_looks_like: 'Financing path firm',
  },
  {
    lib_id: 'RE-15',
    route: 'Both',
    process_stage: 'Closing',
    title: 'Title commitment; closing statement; wire',
    default_priority: 'Critical',
    owner_role: 'Counsel + Ops',
    what_good_looks_like: 'Funded; deed recorded',
  },
  {
    lib_id: 'RE-16',
    route: 'Both',
    process_stage: 'Onboard',
    title: 'Add to RE Portfolio; property manager kickoff',
    default_priority: 'Critical',
    owner_role: 'RE Sourcer + PM',
    what_good_looks_like: 'KPIs live month 1',
  },
];

export function reTemplatesForStage(
  stage: ReStage,
  route: ReRoute,
): ReProcessTemplate[] {
  return RE_PROCESS_LIBRARY.filter(
    (t) =>
      t.process_stage === stage &&
      (t.route === 'Both' || t.route === route),
  );
}
