import type { DealProcessTemplate, ExecStage } from '@/lib/types';

/** Deal Process Library from Excel — spawn into Deal Tasks Active. */
export const DEAL_PROCESS_LIBRARY: DealProcessTemplate[] = [
  {
    lib_id: 'DX-01',
    process_stage: 'IC Approved',
    title: 'Finalize IC memo with DD findings and recommendation',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Memo includes risks, kill criteria, return case',
  },
  {
    lib_id: 'DX-02',
    process_stage: 'IC Approved',
    title: 'Hold IC; record vote and any conditions',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Written approval + conditions logged',
  },
  {
    lib_id: 'DX-03',
    process_stage: 'IC Approved',
    title: 'Open Deal Active row (DE-###); link Lead ID + Company',
    default_priority: 'Critical',
    owner_role: 'Associate',
    what_good_looks_like: 'Same Company string as DD Entity',
  },
  {
    lib_id: 'DX-04',
    process_stage: 'IC Approved',
    title: 'Engage counsel; open matter and conflict check',
    default_priority: 'High',
    owner_role: 'Partner',
    what_good_looks_like: 'Counsel assigned on Deal Active',
  },
  {
    lib_id: 'DX-05',
    process_stage: 'Term Sheet',
    title: 'Draft term sheet economics and key rights',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Valuation, check, ownership, board, pool, pro rata',
  },
  {
    lib_id: 'DX-06',
    process_stage: 'Term Sheet',
    title: 'Internal review of TS vs IC authority',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Within IC band or re-approval noted',
  },
  {
    lib_id: 'DX-07',
    process_stage: 'Term Sheet',
    title: 'Send TS to founder / company counsel',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'TS Sent Date set',
  },
  {
    lib_id: 'DX-08',
    process_stage: 'Term Sheet',
    title: 'Negotiate TS markups; track open commercial points',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Issue list current until signed',
  },
  {
    lib_id: 'DX-09',
    process_stage: 'Term Sheet',
    title: 'Sign term sheet; set exclusivity / no-shop end date',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'TS Signed + Exclusivity End populated',
  },
  {
    lib_id: 'DX-10',
    process_stage: 'Term Sheet',
    title: 'Announce process timeline and working group',
    default_priority: 'High',
    owner_role: 'Associate',
    what_good_looks_like: 'Target Close agreed with company',
  },
  {
    lib_id: 'DX-11',
    process_stage: 'Confirmatory DD',
    title: 'Confirmatory legal DD request list to company counsel',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'Aligned with open DD tracker items',
  },
  {
    lib_id: 'DX-12',
    process_stage: 'Confirmatory DD',
    title: 'Bring-down financials / cap table refresh',
    default_priority: 'Critical',
    owner_role: 'Associate',
    what_good_looks_like: 'No material adverse surprises vs IC',
  },
  {
    lib_id: 'DX-13',
    process_stage: 'Confirmatory DD',
    title: 'IP assignments, employment, and contractor cleanup',
    default_priority: 'High',
    owner_role: 'Counsel',
    what_good_looks_like: 'All core IP owned by company',
  },
  {
    lib_id: 'DX-14',
    process_stage: 'Confirmatory DD',
    title: 'Resolve IC conditions and residual red flags',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Conditions closed or waived in writing',
  },
  {
    lib_id: 'DX-15',
    process_stage: 'Docs Drafting',
    title: 'SPA / investment agreement first draft',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'Reflects signed TS',
  },
  {
    lib_id: 'DX-16',
    process_stage: 'Docs Drafting',
    title: 'IRA, voting, ROFR/co-sale, side letters as needed',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'Package complete for company counsel',
  },
  {
    lib_id: 'DX-17',
    process_stage: 'Docs Drafting',
    title: 'Charter / COI amendments and board consents drafted',
    default_priority: 'High',
    owner_role: 'Counsel',
    what_good_looks_like: 'Ready for stockholder approval path',
  },
  {
    lib_id: 'DX-18',
    process_stage: 'Docs Drafting',
    title: 'SPA markup rounds; maintain issue list to zero',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'No material open points before signing',
  },
  {
    lib_id: 'DX-19',
    process_stage: 'Docs Drafting',
    title: 'Disclosure schedules review',
    default_priority: 'High',
    owner_role: 'Counsel',
    what_good_looks_like: 'Schedules match DD knowledge',
  },
  {
    lib_id: 'DX-20',
    process_stage: 'Signing Ready',
    title: 'Final docs frozen; signature packets prepared',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'All parties on final forms',
  },
  {
    lib_id: 'DX-21',
    process_stage: 'Signing Ready',
    title: 'Fund internal approvals / LP notices if required',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Authority to wire confirmed',
  },
  {
    lib_id: 'DX-22',
    process_stage: 'Signing Ready',
    title: 'Funds flow / wiring instructions verified',
    default_priority: 'Critical',
    owner_role: 'Ops',
    what_good_looks_like: 'Bank details dual-verified',
  },
  {
    lib_id: 'DX-23',
    process_stage: 'Closing Conditions',
    title: 'Closing checklist: consents, good standing, bring-down',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'All CPs satisfied or waived',
  },
  {
    lib_id: 'DX-24',
    process_stage: 'Closing Conditions',
    title: 'Officer certificates and secretary certificates',
    default_priority: 'High',
    owner_role: 'Counsel',
    what_good_looks_like: 'Executed and dated correctly',
  },
  {
    lib_id: 'DX-25',
    process_stage: 'Closing Conditions',
    title: 'Cap table / option pool final pre-close',
    default_priority: 'Critical',
    owner_role: 'Associate',
    what_good_looks_like: 'Matches SPA schedules',
  },
  {
    lib_id: 'DX-26',
    process_stage: 'Wired / Closed',
    title: 'Execute docs; release signatures',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'Fully executed set filed',
  },
  {
    lib_id: 'DX-27',
    process_stage: 'Wired / Closed',
    title: 'Wire funds; confirm receipt',
    default_priority: 'Critical',
    owner_role: 'Ops',
    what_good_looks_like: 'Wire confirmation + company ack',
  },
  {
    lib_id: 'DX-28',
    process_stage: 'Wired / Closed',
    title: 'Close Deal Active → Deal Closed (Wired/Closed)',
    default_priority: 'Critical',
    owner_role: 'Associate',
    what_good_looks_like: 'Close Date + final economics logged',
  },
  {
    lib_id: 'DX-29',
    process_stage: 'Post-Close',
    title: 'Stock certificates / book entry and cap table update',
    default_priority: 'High',
    owner_role: 'Ops',
    what_good_looks_like: 'Ownership reflected in system of record',
  },
  {
    lib_id: 'DX-30',
    process_stage: 'Post-Close',
    title: 'Board seat onboarding and first board calendar',
    default_priority: 'High',
    owner_role: 'Partner',
    what_good_looks_like: 'D&O, calendar, materials process set',
  },
  {
    lib_id: 'DX-31',
    process_stage: 'Post-Close',
    title: 'Portfolio kickoff: reporting, metrics, value-add plan',
    default_priority: 'High',
    owner_role: 'Partner',
    what_good_looks_like: 'Owner and cadence assigned',
  },
  {
    lib_id: 'DX-32',
    process_stage: 'Post-Close',
    title: 'Archive data room + deal folder; lessons learned note',
    default_priority: 'Medium',
    owner_role: 'Associate',
    what_good_looks_like: 'Searchable archive for future deals',
  },
];

export function dealTemplatesForStage(
  stage: ExecStage,
): DealProcessTemplate[] {
  return DEAL_PROCESS_LIBRARY.filter((t) => t.process_stage === stage);
}
