import type { MaProcessTemplate, MaStage } from '@/lib/types';

/** M&A Process Library from Excel — spawn into M&A Tasks Active. */
export const MA_PROCESS_LIBRARY: MaProcessTemplate[] = [
  {
    lib_id: 'MA-01',
    process_stage: 'Sourced',
    title: 'Log target: type (platform/add-on/merger), source, teaser',
    default_priority: 'Critical',
    owner_role: 'Associate',
    what_good_looks_like: 'MA-### row complete',
  },
  {
    lib_id: 'MA-02',
    process_stage: 'Sourced',
    title: 'Strategic fit vs platform / roll-up thesis',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Fit Strong/Med/Weak set',
  },
  {
    lib_id: 'MA-03',
    process_stage: 'CIM Review',
    title: 'Review CIM / financials teaser; build first filter memo',
    default_priority: 'Critical',
    owner_role: 'Associate',
    what_good_looks_like: 'Pass/advance with reasons',
  },
  {
    lib_id: 'MA-04',
    process_stage: 'CIM Review',
    title: 'Normalize revenue/EBITDA; flag add-backs',
    default_priority: 'High',
    owner_role: 'Associate',
    what_good_looks_like: 'Bridge to M&A Model inputs',
  },
  {
    lib_id: 'MA-05',
    process_stage: 'Management Meeting',
    title: 'Management meeting / site visit agenda',
    default_priority: 'High',
    owner_role: 'Partner',
    what_good_looks_like: 'Org, customers, culture probed',
  },
  {
    lib_id: 'MA-06',
    process_stage: 'Management Meeting',
    title: 'Customer and employee reference plan',
    default_priority: 'High',
    owner_role: 'Associate',
    what_good_looks_like: 'Refs scheduled under NDA',
  },
  {
    lib_id: 'MA-07',
    process_stage: 'IOI / Indication',
    title: 'Draft non-binding IOI valuation range + structure',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Cash/earnout/rollover sketch',
  },
  {
    lib_id: 'MA-08',
    process_stage: 'IOI / Indication',
    title: 'IC soft circle on IOI before send',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Authority documented',
  },
  {
    lib_id: 'MA-09',
    process_stage: 'LOI / Exclusivity',
    title: 'Negotiate LOI: price, structure, exclusivity, key terms',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Signed LOI; exclusivity end dated',
  },
  {
    lib_id: 'MA-10',
    process_stage: 'LOI / Exclusivity',
    title: 'Engage counsel; open deal room + request list',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'Request list live',
  },
  {
    lib_id: 'MA-11',
    process_stage: 'Confirmatory DD',
    title: 'Quality of earnings (QoE) engagement',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'Normalized EBITDA locked',
  },
  {
    lib_id: 'MA-12',
    process_stage: 'Confirmatory DD',
    title: 'Legal DD: contracts, employment, litigation, IP, real estate',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'Issue list tracked',
  },
  {
    lib_id: 'MA-13',
    process_stage: 'Confirmatory DD',
    title: 'Tax DD and structure memo',
    default_priority: 'High',
    owner_role: 'Counsel',
    what_good_looks_like: 'Asset vs stock path clear',
  },
  {
    lib_id: 'MA-14',
    process_stage: 'Confirmatory DD',
    title: 'Commercial DD: concentration, churn, pricing power',
    default_priority: 'Critical',
    owner_role: 'Associate',
    what_good_looks_like: 'Top customers validated',
  },
  {
    lib_id: 'MA-15',
    process_stage: 'Confirmatory DD',
    title: 'Ops/IT/HR diligence for integration risk',
    default_priority: 'High',
    owner_role: 'COO',
    what_good_looks_like: 'Systems and people map',
  },
  {
    lib_id: 'MA-16',
    process_stage: 'Confirmatory DD',
    title: 'Update M&A Model + Scorecard; IC full approval',
    default_priority: 'Critical',
    owner_role: 'Partner',
    what_good_looks_like: 'IC vote recorded',
  },
  {
    lib_id: 'MA-17',
    process_stage: 'Definitive Docs',
    title: 'SPA / APA draft and negotiation',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'Reps, indemnities, escrow set',
  },
  {
    lib_id: 'MA-18',
    process_stage: 'Definitive Docs',
    title: 'Employment / rollover / non-compete packages',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'Key people locked',
  },
  {
    lib_id: 'MA-19',
    process_stage: 'Definitive Docs',
    title: 'Financing / funds flow confirmed',
    default_priority: 'Critical',
    owner_role: 'Ops',
    what_good_looks_like: 'Sources & uses final',
  },
  {
    lib_id: 'MA-20',
    process_stage: 'Closing',
    title: 'Closing checklist: consents, third-party, payoff letters',
    default_priority: 'Critical',
    owner_role: 'Counsel',
    what_good_looks_like: 'All CPs satisfied',
  },
  {
    lib_id: 'MA-21',
    process_stage: 'Closing',
    title: 'Sign and fund; confirm wire and title transfer',
    default_priority: 'Critical',
    owner_role: 'Ops',
    what_good_looks_like: 'Closed; MA pipeline → Acquired',
  },
  {
    lib_id: 'MA-22',
    process_stage: 'Integration',
    title: 'Day-1 / Day-100 integration plan (see M&A Integration)',
    default_priority: 'Critical',
    owner_role: 'COO',
    what_good_looks_like: 'Owners and KPIs named',
  },
  {
    lib_id: 'MA-23',
    process_stage: 'Integration',
    title: 'Systems, brand, reporting cutover',
    default_priority: 'High',
    owner_role: 'COO',
    what_good_looks_like: 'No silent operational break',
  },
  {
    lib_id: 'MA-24',
    process_stage: 'Integration',
    title: 'Synergy tracking vs model; 90-day review',
    default_priority: 'High',
    owner_role: 'Partner + COO',
    what_good_looks_like: 'Variance explained',
  },
];

export function maTemplatesForStage(stage: MaStage): MaProcessTemplate[] {
  return MA_PROCESS_LIBRARY.filter((t) => t.process_stage === stage);
}
